export default {
  header: document.querySelector('.header'),
  nav: document.querySelector('.nav'),
  logo: document.querySelector('.logo'),
  home: document.querySelector('#home'),
  myLib: document.querySelector('#lib'),
  searchBox: document.querySelector('.search-box'),
  input: document.querySelector('#input'),
  notification: document.querySelector('#notification'),
  btnBox: document.querySelector('.btn-box'),
  gallery: document.querySelector('.movies-list'),
  container: document.querySelector('.container'),
  spinner: document.querySelector('.spinner-border'),
  error: document.querySelector('#error'),
};
